const WORDS = [
  { id: 1, word: "print", meaning: "打印；输出", tip: "把内容显示到屏幕上。", category: "基础入门", example: 'print("Hello, Python!")' },
  { id: 2, word: "input", meaning: "输入", tip: "接收用户在键盘里输入的内容。", category: "基础入门", example: 'name = input("请输入姓名：")' },
  { id: 3, word: "variable", meaning: "变量", tip: "用一个名字暂时保存数据。", category: "基础入门", example: "score = 100" },
  { id: 4, word: "comment", meaning: "注释", tip: "写给人看的说明文字，程序不会执行。", category: "基础入门", example: "# 这是一个注释" },
  { id: 5, word: "output", meaning: "输出", tip: "程序运行后展示出来的结果。", category: "基础入门", example: 'print("结果已输出")' },
  { id: 6, word: "code", meaning: "代码", tip: "程序员写给计算机执行的指令。", category: "基础入门", example: "code = 'print(1)'" },
  { id: 7, word: "import", meaning: "导入", tip: "把别的模块功能拿进来使用。", category: "基础入门", example: "import math" },
  { id: 8, word: "module", meaning: "模块", tip: "装着一组功能的 Python 文件。", category: "基础入门", example: "import random  # random 是模块" },
  { id: 9, word: "file", meaning: "文件", tip: "保存在电脑里的数据载体。", category: "基础入门", example: 'with open("note.txt") as file:' },
  { id: 10, word: "debug", meaning: "调试", tip: "查找并修复程序问题的过程。", category: "基础入门", example: 'print("debug:", value)' },

  { id: 11, word: "string", meaning: "字符串", tip: "由文字组成的数据，通常放在引号里。", category: "数据类型", example: 'language = "Python"' },
  { id: 12, word: "integer", meaning: "整数", tip: "没有小数点的数字。", category: "数据类型", example: "age = 18" },
  { id: 13, word: "float", meaning: "浮点数", tip: "带小数点的数字。", category: "数据类型", example: "price = 19.9" },
  { id: 14, word: "boolean", meaning: "布尔值", tip: "只有 True 和 False 两种结果。", category: "数据类型", example: "is_ready = True" },
  { id: 15, word: "list", meaning: "列表", tip: "用方括号装一组有顺序的数据。", category: "数据类型", example: 'colors = ["red", "blue"]' },
  { id: 16, word: "tuple", meaning: "元组", tip: "和列表很像，但创建后不方便修改。", category: "数据类型", example: "point = (10, 20)" },
  { id: 17, word: "dict", meaning: "字典", tip: "用键和值配对保存数据。", category: "数据类型", example: 'user = {"name": "Tom"}' },
  { id: 18, word: "set", meaning: "集合", tip: "一组不重复的数据。", category: "数据类型", example: "numbers = {1, 2, 3}" },
  { id: 19, word: "index", meaning: "索引", tip: "元素在序列里的位置编号。", category: "数据类型", example: 'name[0]  # 第一个字符' },
  { id: 20, word: "key", meaning: "键", tip: "字典里用来查找值的名字。", category: "数据类型", example: 'user["name"]' },

  { id: 21, word: "if", meaning: "如果", tip: "条件成立时执行后面的代码。", category: "流程控制", example: "if score > 60:" },
  { id: 22, word: "else", meaning: "否则", tip: "当前面的条件不成立时执行。", category: "流程控制", example: "else:\n    print('继续努力')" },
  { id: 23, word: "elif", meaning: "否则如果", tip: "在 if 和 else 之间继续判断其他条件。", category: "流程控制", example: "elif score == 60:" },
  { id: 24, word: "for", meaning: "循环遍历", tip: "按顺序一个一个处理数据。", category: "流程控制", example: "for item in items:" },
  { id: 25, word: "while", meaning: "当……时循环", tip: "只要条件满足就一直执行。", category: "流程控制", example: "while count < 3:" },
  { id: 26, word: "break", meaning: "跳出循环", tip: "提前结束整个循环。", category: "流程控制", example: "if item == 0:\n    break" },
  { id: 27, word: "continue", meaning: "继续下一轮", tip: "跳过当前这次循环，直接进入下一次。", category: "流程控制", example: "if item < 0:\n    continue" },
  { id: 28, word: "loop", meaning: "循环", tip: "重复执行某段代码的结构。", category: "流程控制", example: "# for loop / while loop" },
  { id: 29, word: "condition", meaning: "条件", tip: "决定程序是否执行某条分支的判断。", category: "流程控制", example: "condition = score > 60" },
  { id: 30, word: "range", meaning: "范围序列", tip: "常用来生成一串数字配合循环使用。", category: "流程控制", example: "for i in range(5):" },

  { id: 31, word: "function", meaning: "函数", tip: "把一段可重复使用的逻辑打包成名字。", category: "函数基础", example: "def greet():\n    print('Hi')" },
  { id: 32, word: "return", meaning: "返回", tip: "把函数计算后的结果交出去。", category: "函数基础", example: "return total" },
  { id: 33, word: "argument", meaning: "实参", tip: "调用函数时传进去的具体值。", category: "函数基础", example: 'print("Hello")  # "Hello" 是 argument' },
  { id: 34, word: "parameter", meaning: "形参", tip: "函数定义时准备接收值的变量名。", category: "函数基础", example: "def greet(name):" },
  { id: 35, word: "def", meaning: "定义函数", tip: "Python 里创建函数的关键字。", category: "函数基础", example: "def add(a, b):" },
  { id: 36, word: "call", meaning: "调用", tip: "让函数真正运行起来。", category: "函数基础", example: "greet()  # call the function" },
  { id: 37, word: "method", meaning: "方法", tip: "对象自带的函数。", category: "函数基础", example: 'name.upper()  # upper 是 method' },
  { id: 38, word: "class", meaning: "类", tip: "用来创建对象的模板。", category: "函数基础", example: "class Student:" },
  { id: 39, word: "object", meaning: "对象", tip: "根据类创建出来的具体实例。", category: "函数基础", example: "student = Student()" },
  { id: 40, word: "instance", meaning: "实例", tip: "对象的另一种常见叫法。", category: "函数基础", example: "isinstance(student, Student)" },

  { id: 41, word: "error", meaning: "错误", tip: "程序运行或书写时出现的问题。", category: "常见报错词", example: 'print("有 error 需要处理")' },
  { id: 42, word: "syntax", meaning: "语法", tip: "代码书写规则本身。", category: "常见报错词", example: "# SyntaxError 表示语法写错了" },
  { id: 43, word: "invalid", meaning: "无效的", tip: "输入或写法不符合要求。", category: "常见报错词", example: "# invalid syntax" },
  { id: 44, word: "type", meaning: "类型", tip: "数据属于哪一种形式。", category: "常见报错词", example: "type(123)" },
  { id: 45, word: "name", meaning: "名称", tip: "变量名、函数名这类标识符。", category: "常见报错词", example: "# NameError 常见于变量名写错" },
  { id: 46, word: "value", meaning: "值", tip: "变量里真正存放的内容。", category: "常见报错词", example: "value = 42" },
  { id: 47, word: "attribute", meaning: "属性", tip: "对象身上保存的数据或能力。", category: "常见报错词", example: 'user.name  # name 是 attribute' },
  { id: 48, word: "indent", meaning: "缩进", tip: "Python 用空格控制代码层级。", category: "常见报错词", example: "if ok:\n    print('yes')" },
  { id: 49, word: "exception", meaning: "异常", tip: "程序运行过程中抛出的错误情况。", category: "常见报错词", example: "except Exception as error:" },
  { id: 50, word: "traceback", meaning: "报错追踪信息", tip: "告诉你错误发生在什么位置。", category: "常见报错词", example: "# Traceback 会显示报错调用链" }
];
